apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: test
          image: localhost:5000/web-test
          ports:
            - containerPort: 8081
