apiVersion: v1
kind: Service
metadata:
  name: web-service-external
  namespace: test
spec:
  selector:
    app: web-app
  ports:
  - name: http
    port: 9091
    targetPort: 8081
    nodePort: 30006
  type: NodePort
